apiVersion: batch/v1
kind: Job
metadata:
  name: hello-job
spec:
  template:
    spec:
      containers:
      - name: hello-job-container
        image: ubuntu
        command:
        - "/bin/bash"
        - "-c"
        - "/bin/echo Hello from pod-job ${hostname} a las ${date}"
      restartPolicy: Never

