apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-local-data
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /Users/livierortegavelazquez/Documents/GitHub/EcosistemaJenkins/kubernetesdata